name: multipass
description: SpookyID Relay Application (Zero-Trust)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Native Bridge
  # uniffi: ^0.1.0 (Using local generation)
  flutter_nfc_kit: ^3.4.0
  provider: ^6.0.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  ffi: ^2.1.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.0
  flutter_rust_bridge: 2.11.1
  mobile_scanner: ^5.0.0
  qr_flutter: ^4.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
